#!/bin/zsh -f
# project

local name=$1 project_template=~/Source/.project-template/
local dest=~/Source/$name

if [[ -e $dest ]]; then
  print -u2 "Unable to create project ${name}: ${dest} already exists"
  return 1
fi
mkdir -p $(dirname $dest)

cp -r $project_template $dest
cd $dest
git init .
print -l ".envrc" ".ipython" >>./.git/info/exclude
direnv allow . && pip install -r requirements.txt
